import path = require("path");
import { parseSystem, System } from "../api";
import { Value } from "../common";
import { Entities, FullEntity, readEntities } from "../entities";
import { parseEntityValues } from "../entityvalue";
import { disableWarnings } from "../util";

export const ENTITIES_CSV_3_7_PATH = "config/dump_entities.csv";
export const ENTITIES_CSV_3_5_PATH = "config/dump_entities.csv.20230128";
export const ENTITIES_CSV_PATH = ENTITIES_CSV_3_7_PATH;

export async function getParsedEntities(
    csv_path: string = ENTITIES_CSV_PATH,
): Promise<FullEntity[]> {
    const entitiesPath = path.resolve(__dirname, "../..", csv_path);
    return readEntities(entitiesPath);
}

export function getExampleSystem_3_5(): System {
    return parseSystem(JSON.parse(EXAMPLE_SYSTEM_RESPONSE_3_5));
}

export function getExampleSystem_3_7(): System {
    return parseSystem(JSON.parse(EXAMPLE_SYSTEM_RESPONSE_3_7));
}

export async function getExampleDeviceValues_3_5(): Promise<Value[]> {
    try {
        disableWarnings(true); // 3.5 has issues with duplicate entries
        const entities = new Entities(
            await getParsedEntities(ENTITIES_CSV_3_5_PATH),
        );
        return entities.parseValues(
            115,
            JSON.parse(EXAMPLE_DEVICE_RESPONSE_3_5),
        );
    } finally {
        disableWarnings(false);
    }
}

export async function getExampleDeviceValues_3_7(): Promise<Value[]> {
    const entities = new Entities(
        await getParsedEntities(ENTITIES_CSV_3_7_PATH),
    );
    return entities.parseValues(115, JSON.parse(EXAMPLE_DEVICE_RESPONSE_3_7));
}

export function getExampleEntityValues_3_7(): Value[] {
    return parseEntityValues(JSON.parse(EXAMPLE_ENTITIES_RESPONSE_3_7));
}

export const EXAMPLE_SYSTEM_RESPONSE_3_5 = `{
    "System Info": {
      "version": "3.5.1-dev.0",
      "platform": "ESP32",
      "uptime": "007+11:10:36.612",
      "uptime (seconds)": 645036,
      "free mem": 117,
      "max alloc": 65,
      "free app": 6152,
      "reset reason": "Timer group1 watch dog reset / APP CPU reset by PRO CPU"
    },
    "Network Info": {
      "network": "WiFi",
      "hostname": "ems-esp",
      "RSSI": -57,
      "IPv4 address": "192.168.3.15/255.255.255.0",
      "IPv4 gateway": "192.168.3.1",
      "IPv4 nameserver": "192.168.3.1",
      "static ip config": false,
      "enable IPv6": false,
      "low bandwidth": false,
      "disable sleep": false,
      "enable MDNS": true,
      "enable CORS": false,
      "AP provision mode": "disconnected",
      "AP security": "wpa2",
      "AP ssid": "ems-esp"
    },
    "NTP Info": {
      "NTP status": "connected",
      "enabled": true,
      "server": "nl.pool.ntp.org",
      "tz label": "Europe/Amsterdam"
    },
    "OTA Info": {
      "enabled": false,
      "port": 8266
    },
    "MQTT Info": {
      "MQTT status": "connected",
      "MQTT publishes": 140592,
      "MQTT queued": 0,
      "MQTT publish fails": 0,
      "MQTT connects": 1,
      "enabled": true,
      "client id": "ems-esp",
      "keep alive": 60,
      "clean session": true,
      "entity format": 0,
      "base": "ems-esp",
      "discovery prefix": "homeassistant",
      "nested format": 1,
      "ha enabled": true,
      "mqtt qos": 0,
      "mqtt retain": false,
      "publish time heartbeat": 60,
      "publish time boiler": 10,
      "publish time thermostat": 10,
      "publish time solar": 10,
      "publish time mixer": 10,
      "publish time other": 10,
      "publish time sensor": 10,
      "publish single": false,
      "publish2command": false,
      "send response": false
    },
    "Syslog Info": {
      "enabled": false
    },
    "Sensor Info": {
      "temperature sensors": 0,
      "temperature sensor reads": 0,
      "temperature sensor fails": 0,
      "analog sensors": 0,
      "analog sensor reads": 0,
      "analog sensor fails": 0
    },
    "API Info": {
      "API calls": 137014,
      "API fails": 2
    },
    "Bus Info": {
      "bus status": "connected",
      "bus protocol": "Buderus",
      "bus telegrams received (rx)": 266780,
      "bus reads (tx)": 35526,
      "bus writes (tx)": 7978,
      "bus incomplete telegrams": 5,
      "bus reads failed": 0,
      "bus writes failed": 0,
      "bus rx line quality": 100,
      "bus tx line quality": 100
    },
    "Settings": {
      "board profile": "S32",
      "locale": "en",
      "tx mode": 1,
      "ems bus id": 11,
      "shower timer": false,
      "shower alert": false,
      "hide led": false,
      "notoken api": false,
      "readonly mode": false,
      "fahrenheit": false,
      "dallas parasite": false,
      "bool format": 1,
      "bool dashboard": 1,
      "enum format": 1,
      "analog enabled": true,
      "telnet enabled": true,
      "max web log buffer": 50,
      "web log buffer": 50
    },
    "Devices": [
      {
        "type": "boiler",
        "name": "Topline/GB162",
        "device id": "0x08",
        "product id": 115,
        "version": "03.06",
        "entities": 68,
        "handlers received": "0x10 0x11 0x15 0x1C 0x18 0x19 0x34",
        "handlers fetched": "0x14 0x16 0x33",
        "handlers pending": "0xBF 0xC2 0x1A 0x35 0x26 0x2A 0xD1 0xE3 0xE4 0xE5 0xE6 0xE9 0xEA"
      },
      {
        "type": "controller",
        "name": "BC10",
        "device id": "0x09",
        "product id": 114,
        "version": "01.03",
        "entities": 0
      }
    ]
  }`;

export const EXAMPLE_DEVICE_RESPONSE_3_5 = `{
    "wwsettemp": 61,
    "wwseltemp": 60,
    "wwtype": "buffer",
    "wwcomfort": "hot",
    "wwflowtempoffset": 20,
    "wwcircpump": "on",
    "wwchargetype": "3-way valve",
    "wwhyston": -11,
    "wwhystoff": 0,
    "wwdisinfectiontemp": 70,
    "wwcircmode": "2x3min",
    "wwcirc": "off",
    "wwcurtemp": 43.3,
    "wwcurtemp2": 58.9,
    "wwcurflow": 0.0,
    "wwstoragetemp1": 43.3,
    "wwstoragetemp2": 58.9,
    "wwactivated": "on",
    "wwonetime": "off",
    "wwdisinfecting": "off",
    "wwcharging": "off",
    "wwrecharging": "off",
    "wwtempok": "on",
    "wwactive": "off",
    "ww3wayvalve": "off",
    "wwstarts": 29519,
    "wwworkm": 192694,
    "heatingactive": "off",
    "tapwateractive": "off",
    "selflowtemp": 20,
    "heatingpumpmod": 60,
    "curflowtemp": 25.3,
    "rettemp": 25.5,
    "switchtemp": 0.0,
    "syspress": 0.9,
    "boiltemp": 24.1,
    "burngas": "off",
    "burngas2": "off",
    "flamecurr": 0.0,
    "heatingpump": "on",
    "fanwork": "off",
    "ignwork": "off",
    "oilpreheat": "off",
    "heatingactivated": "on",
    "heatingtemp": 80,
    "pumpmodmax": 100,
    "pumpmodmin": 60,
    "pumpmode": "proportional",
    "pumpdelay": 12,
    "burnminperiod": 10,
    "burnminpower": 0,
    "burnmaxpower": 80,
    "boilhyston": -6,
    "boilhystoff": 6,
    "selburnpow": 80,
    "curburnpow": 0,
    "burnstarts": 136369,
    "burnworkmin": 1184044,
    "burn2workmin": 0,
    "heatworkmin": 991350,
    "heatstarts": 106850,
    "ubauptime": 8939385,
    "servicecode": "0Y",
    "servicecodenumber": 204,
    "maintenancemessage": "H00",
    "maintenance": "off",
    "maintenancetime": 6000,
    "maintenancedate": "01.01.2004"
  }`;

export const EXAMPLE_SYSTEM_RESPONSE_3_7 = `{
    "system": {
        "version": "3.7.1",
        "uptime": "000+00:01:04.366",
        "uptimeSec": 64,
        "platform": "ESP32",
        "cpuType": "ESP32-D0WD-V3",
        "arduino": "Tasmota Arduino v2.0.17",
        "sdk": "4.4.8.240628",
        "freeMem": 175,
        "maxAlloc": 107,
        "freeCaps": 125,
        "usedApp": 1740,
        "freeApp": 6388,
        "partition": "app1",
        "resetReason": "Software reset CPU / Software reset CPU",
        "psram": false,
        "model": ""
    },
    "network": {
        "network": "WiFi",
        "hostname": "ems-esp",
        "RSSI": -56,
        "WIFIReconnects": 0,
        "TxPowerSetting": 78,
        "staticIP": false,
        "lowBandwidth": false,
        "disableSleep": true,
        "enableMDNS": true,
        "enableCORS": false,
        "APProvisionMode": "disconnected",
        "APSecurity": "wpa2",
        "APSSID": "ems-esp"
    },
    "ntp": {
        "NTPStatus": "connected",
        "enabled": true,
        "server": "nl.pool.ntp.org",
        "tzLabel": "Europe/Amsterdam"
    },
    "mqtt": {
        "MQTTStatus": "connected",
        "MQTTPublishes": 102,
        "MQTTQueued": 0,
        "MQTTPublishFails": 0,
        "MQTTReconnects": 0,
        "enabled": true,
        "clientID": "ems-esp",
        "keepAlive": 60,
        "cleanSession": true,
        "entityFormat": 0,
        "base": "ems-esp",
        "discoveryPrefix": "homeassistant",
        "discoveryType": 0,
        "nestedFormat": 1,
        "haEnabled": true,
        "mqttQos": 0,
        "mqttRetain": false,
        "publishTimeHeartbeat": 60,
        "publishTimeBoiler": 10,
        "publishTimeThermostat": 10,
        "publishTimeSolar": 10,
        "publishTimeMixer": 10,
        "publishTimeWater": 10,
        "publishTimeOther": 10,
        "publishTimeSensor": 10,
        "publishSingle": false,
        "publish2command": false,
        "sendResponse": false
    },
    "syslog": {
        "enabled": false
    },
    "sensor": {
        "temperatureSensors": 0,
        "temperatureSensorReads": 0,
        "temperatureSensorFails": 0,
        "analogSensors": 0,
        "analogSensorReads": 0,
        "analogSensorFails": 0
    },
    "api": {
        "APICalls": 8,
        "APIFails": 0
    },
    "bus": {
        "busStatus": "connected",
        "busProtocol": "Buderus",
        "busTelegramsReceived": 80,
        "busReads": 30,
        "busWrites": 1,
        "busIncompleteTelegrams": 0,
        "busReadsFailed": 0,
        "busWritesFailed": 0,
        "busRxLineQuality": 100,
        "busTxLineQuality": 100
    },
    "settings": {
        "boardProfile": "S32",
        "locale": "en",
        "txMode": 1,
        "emsBusID": 11,
        "showerTimer": false,
        "showerMinDuration": 180,
        "showerAlert": false,
        "hideLed": false,
        "noTokenApi": false,
        "readonlyMode": false,
        "fahrenheit": false,
        "dallasParasite": false,
        "boolFormat": 1,
        "boolDashboard": 1,
        "enumFormat": 1,
        "analogEnabled": true,
        "telnetEnabled": true,
        "maxWebLogBuffer": 25,
        "webLogBuffer": 18,
        "modbusEnabled": false,
        "forceHeatingOff": false,
        "developerMode": false
    },
    "devices": [
        {
            "type": "boiler",
            "name": "Topline, GB162",
            "deviceID": "0x08",
            "productID": 115,
            "brand": "",
            "version": "03.06",
            "entities": 74,
            "handlersReceived": "0x10 0x11 0x15 0x1C 0x18 0x19 0x34 0x04",
            "handlersFetched": "0x14 0x16 0x33",
            "handlersPending": "0xBF 0xC2 0x1A 0x35 0x2A 0xD1 0xE3 0xE4 0xE5 0xE9 0x2E 0x3B"
        },
        {
            "type": "controller",
            "name": "BC10",
            "deviceID": "0x09",
            "productID": 114,
            "brand": "",
            "version": "01.03",
            "entities": 0
        }
    ]
}`;

export const EXAMPLE_DEVICE_RESPONSE_3_7 = `{
    "reset": "",
    "heatingoff": "off",
    "heatingactive": "on",
    "tapwateractive": "off",
    "selflowtemp": 70,
    "heatingpumpmod": 71,
    "curflowtemp": 70.1,
    "rettemp": 58.7,
    "switchtemp": 0.0,
    "syspress": 1.5,
    "boiltemp": 66.4,
    "burngas": "on",
    "burngas2": "off",
    "flamecurr": 23.0,
    "fanwork": "on",
    "ignwork": "off",
    "oilpreheat": "off",
    "burnminpower": 0,
    "burnmaxpower": 80,
    "burnminperiod": 10,
    "boilhyston": -6,
    "boilhystoff": 6,
    "heatingactivated": "on",
    "heatingtemp": 80,
    "heatingpump": "on",
    "pumpmodmax": 100,
    "pumpmodmin": 60,
    "pumpmode": "proportional",
    "pumpdelay": 12,
    "selburnpow": 80,
    "curburnpow": 34,
    "burnstarts": 136570,
    "burnworkmin": 1188977,
    "burn2workmin": 0,
    "heatworkmin": 996060,
    "heatstarts": 107037,
    "ubauptime": 8949480,
    "servicecode": "-H",
    "servicecodenumber": 200,
    "maintenancemessage": "H00",
    "maintenance": "off",
    "maintenancetime": 6000,
    "maintenancedate": "01.01.2004",
    "nompower": 30,
    "nrgtotal": 2.25,
    "nrgheat": 2.25,
    "dhw": {
        "settemp": 61,
        "seltemp": 60,
        "type": "buffer",
        "comfort": "hot",
        "flowtempoffset": 20,
        "circpump": "on",
        "chargetype": "3-way valve",
        "hyston": -11,
        "hystoff": 0,
        "disinfectiontemp": 70,
        "circmode": "2x3min",
        "circ": "off",
        "curtemp": 46.1,
        "curtemp2": 60.2,
        "curflow": 0.0,
        "storagetemp1": 46.0,
        "storagetemp2": 60.2,
        "activated": "on",
        "onetime": "off",
        "disinfecting": "off",
        "charging": "off",
        "recharging": "off",
        "tempok": "on",
        "active": "off",
        "3wayvalve": "off",
        "starts": 29533,
        "workm": 192917,
        "nrg": 0.00
    }
}`;

export const EXAMPLE_ENTITIES_RESPONSE_3_7 = `{
    "reset": {
        "name": "reset",
        "fullname": "reset",
        "circuit": "",
        "type": "enum",
        "enum": [
            "-",
            "maintenance",
            "error",
            "history",
            "message"
        ],
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "heatingoff": {
        "name": "heatingoff",
        "fullname": "force heating off",
        "circuit": "",
        "bool": false,
        "index": 0,
        "value": "off",
        "type": "boolean",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "heatingactive": {
        "name": "heatingactive",
        "fullname": "heating active",
        "circuit": "",
        "bool": false,
        "index": 0,
        "value": "off",
        "type": "boolean",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "tapwateractive": {
        "name": "tapwateractive",
        "fullname": "tapwater active",
        "circuit": "",
        "bool": false,
        "index": 0,
        "value": "off",
        "type": "boolean",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "selflowtemp": {
        "name": "selflowtemp",
        "fullname": "selected flow temperature",
        "circuit": "",
        "value": 7,
        "type": "number",
        "min": 0,
        "max": 90,
        "uom": "°C",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "heatingpumpmod": {
        "name": "heatingpumpmod",
        "fullname": "heating pump modulation",
        "circuit": "",
        "value": 0,
        "type": "number",
        "uom": "%",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "outdoortemp": {
        "name": "outdoortemp",
        "fullname": "outside temperature",
        "circuit": "",
        "type": "number",
        "uom": "°C",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "curflowtemp": {
        "name": "curflowtemp",
        "fullname": "current flow temperature",
        "circuit": "",
        "value": 51.8,
        "type": "number",
        "uom": "°C",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "rettemp": {
        "name": "rettemp",
        "fullname": "return temperature",
        "circuit": "",
        "value": 56.1,
        "type": "number",
        "uom": "°C",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "switchtemp": {
        "name": "switchtemp",
        "fullname": "mixing switch temperature",
        "circuit": "",
        "value": 0.0,
        "type": "number",
        "uom": "°C",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "syspress": {
        "name": "syspress",
        "fullname": "system pressure",
        "circuit": "",
        "value": 0.9,
        "type": "number",
        "uom": "bar",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "boiltemp": {
        "name": "boiltemp",
        "fullname": "actual boiler temperature",
        "circuit": "",
        "value": 60.5,
        "type": "number",
        "uom": "°C",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "headertemp": {
        "name": "headertemp",
        "fullname": "low loss header",
        "circuit": "",
        "type": "number",
        "uom": "°C",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "exhausttemp": {
        "name": "exhausttemp",
        "fullname": "exhaust temperature",
        "circuit": "",
        "type": "number",
        "uom": "°C",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "burngas": {
        "name": "burngas",
        "fullname": "gas",
        "circuit": "",
        "bool": false,
        "index": 0,
        "value": "off",
        "type": "boolean",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "burngas2": {
        "name": "burngas2",
        "fullname": "gas stage 2",
        "circuit": "",
        "bool": false,
        "index": 0,
        "value": "off",
        "type": "boolean",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "flamecurr": {
        "name": "flamecurr",
        "fullname": "flame current",
        "circuit": "",
        "value": 0.0,
        "type": "number",
        "uom": "µA",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "fanwork": {
        "name": "fanwork",
        "fullname": "fan",
        "circuit": "",
        "bool": false,
        "index": 0,
        "value": "off",
        "type": "boolean",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "ignwork": {
        "name": "ignwork",
        "fullname": "ignition",
        "circuit": "",
        "bool": false,
        "index": 0,
        "value": "off",
        "type": "boolean",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "oilpreheat": {
        "name": "oilpreheat",
        "fullname": "oil preheating",
        "circuit": "",
        "bool": false,
        "index": 0,
        "value": "off",
        "type": "boolean",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "burnminpower": {
        "name": "burnminpower",
        "fullname": "burner min power",
        "circuit": "",
        "value": 0,
        "type": "number",
        "min": 0,
        "max": 100,
        "uom": "%",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "burnmaxpower": {
        "name": "burnmaxpower",
        "fullname": "burner max power",
        "circuit": "",
        "value": 80,
        "type": "number",
        "min": 17,
        "max": 100,
        "uom": "%",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "burnminperiod": {
        "name": "burnminperiod",
        "fullname": "burner min period",
        "circuit": "",
        "value": 10,
        "type": "number",
        "min": 0,
        "max": 120,
        "uom": "minutes",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "absburnpow": {
        "name": "absburnpow",
        "fullname": "burner current power (absolute)",
        "circuit": "",
        "type": "number",
        "uom": "%",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "heatblock": {
        "name": "heatblock",
        "fullname": "heating block",
        "circuit": "",
        "type": "number",
        "uom": "°C",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "boilhyston": {
        "name": "boilhyston",
        "fullname": "hysteresis on temperature",
        "circuit": "",
        "value": -6,
        "type": "number",
        "min": -20,
        "max": 0,
        "uom": "°C",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "boilhystoff": {
        "name": "boilhystoff",
        "fullname": "hysteresis off temperature",
        "circuit": "",
        "value": 6,
        "type": "number",
        "min": 0,
        "max": 20,
        "uom": "°C",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "boil2hyston": {
        "name": "boil2hyston",
        "fullname": "hysteresis stage 2 on temperature",
        "circuit": "",
        "type": "number",
        "min": -20,
        "max": 0,
        "uom": "°C",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "boil2hystoff": {
        "name": "boil2hystoff",
        "fullname": "hysteresis stage 2 off temperature",
        "circuit": "",
        "type": "number",
        "min": 0,
        "max": 20,
        "uom": "°C",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "curveon": {
        "name": "curveon",
        "fullname": "heatingcurve on",
        "circuit": "",
        "type": "boolean",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "curvebase": {
        "name": "curvebase",
        "fullname": "heatingcurve base",
        "circuit": "",
        "type": "number",
        "min": 20,
        "max": 90,
        "uom": "°C",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "curveend": {
        "name": "curveend",
        "fullname": "heatingcurve end",
        "circuit": "",
        "type": "number",
        "min": 20,
        "max": 90,
        "uom": "°C",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "summertemp": {
        "name": "summertemp",
        "fullname": "summer temperature",
        "circuit": "",
        "type": "number",
        "min": 0,
        "max": 45,
        "uom": "°C",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "nofrostmode": {
        "name": "nofrostmode",
        "fullname": "nofrost mode",
        "circuit": "",
        "type": "boolean",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "nofrosttemp": {
        "name": "nofrosttemp",
        "fullname": "nofrost temperature",
        "circuit": "",
        "type": "number",
        "min": 0,
        "max": 10,
        "uom": "°C",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "heatingactivated": {
        "name": "heatingactivated",
        "fullname": "heating activated",
        "circuit": "",
        "bool": true,
        "index": 1,
        "value": "on",
        "type": "boolean",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "heatingtemp": {
        "name": "heatingtemp",
        "fullname": "heating temperature",
        "circuit": "",
        "value": 80,
        "type": "number",
        "min": 0,
        "max": 90,
        "uom": "°C",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "heatingpump": {
        "name": "heatingpump",
        "fullname": "heating pump",
        "circuit": "",
        "bool": false,
        "index": 0,
        "value": "off",
        "type": "boolean",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "pumpmodmax": {
        "name": "pumpmodmax",
        "fullname": "boiler pump max power",
        "circuit": "",
        "value": 100,
        "type": "number",
        "min": 0,
        "max": 100,
        "uom": "%",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "pumpmodmin": {
        "name": "pumpmodmin",
        "fullname": "boiler pump min power",
        "circuit": "",
        "value": 60,
        "type": "number",
        "min": 0,
        "max": 100,
        "uom": "%",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "pumpmode": {
        "name": "pumpmode",
        "fullname": "boiler pump mode",
        "circuit": "",
        "index": 0,
        "enum": [
            "proportional",
            "deltaP-1",
            "deltaP-2",
            "deltaP-3",
            "deltaP-4"
        ],
        "value": "proportional",
        "type": "enum",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "pumpcharacter": {
        "name": "pumpcharacter",
        "fullname": "boiler pump characteristic",
        "circuit": "",
        "type": "enum",
        "enum": [
            "proportional",
            "150mbar",
            "200mbar",
            "250mbar",
            "300mbar",
            "350mbar",
            "400mbar"
        ],
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "pumpdelay": {
        "name": "pumpdelay",
        "fullname": "pump delay",
        "circuit": "",
        "value": 12,
        "type": "number",
        "min": 0,
        "max": 60,
        "uom": "minutes",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "pumpontemp": {
        "name": "pumpontemp",
        "fullname": "pump logic temperature",
        "circuit": "",
        "type": "number",
        "min": 0,
        "max": 60,
        "uom": "°C",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "selburnpow": {
        "name": "selburnpow",
        "fullname": "burner selected max power",
        "circuit": "",
        "value": 0,
        "type": "number",
        "min": 0,
        "max": 114,
        "uom": "%",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "curburnpow": {
        "name": "curburnpow",
        "fullname": "burner current power",
        "circuit": "",
        "value": 0,
        "type": "number",
        "uom": "%",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "burnstarts": {
        "name": "burnstarts",
        "fullname": "burner starts",
        "circuit": "",
        "value": 136578,
        "type": "number",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "burnworkmin": {
        "name": "burnworkmin",
        "fullname": "total burner operating time",
        "circuit": "",
        "value": 1189552,
        "type": "number",
        "uom": "minutes",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "burn2workmin": {
        "name": "burn2workmin",
        "fullname": "burner stage 2 operating time",
        "circuit": "",
        "value": 0,
        "type": "number",
        "uom": "minutes",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "heatworkmin": {
        "name": "heatworkmin",
        "fullname": "total heat operating time",
        "circuit": "",
        "value": 996630,
        "type": "number",
        "uom": "minutes",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "heatstarts": {
        "name": "heatstarts",
        "fullname": "burner starts heating",
        "circuit": "",
        "value": 107044,
        "type": "number",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "ubauptime": {
        "name": "ubauptime",
        "fullname": "total UBA operating time",
        "circuit": "",
        "value": 8950188,
        "type": "number",
        "uom": "minutes",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "lastcode": {
        "name": "lastcode",
        "fullname": "last error code",
        "circuit": "",
        "type": "string",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "servicecode": {
        "name": "servicecode",
        "fullname": "service code",
        "circuit": "",
        "value": "0H",
        "type": "string",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "servicecodenumber": {
        "name": "servicecodenumber",
        "fullname": "service code number",
        "circuit": "",
        "value": 203,
        "type": "number",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "maintenancemessage": {
        "name": "maintenancemessage",
        "fullname": "maintenance message",
        "circuit": "",
        "value": "H00",
        "type": "string",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "maintenance": {
        "name": "maintenance",
        "fullname": "maintenance scheduled",
        "circuit": "",
        "index": 0,
        "enum": [
            "off",
            "time",
            "date",
            "manual"
        ],
        "value": "off",
        "type": "enum",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "maintenancetime": {
        "name": "maintenancetime",
        "fullname": "time to next maintenance",
        "circuit": "",
        "value": 6000,
        "type": "number",
        "min": 0,
        "max": 31999,
        "uom": "hours",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "maintenancedate": {
        "name": "maintenancedate",
        "fullname": "next maintenance date",
        "circuit": "",
        "value": "01.01.2004",
        "type": "string",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "emergencyops": {
        "name": "emergencyops",
        "fullname": "emergency operation",
        "circuit": "",
        "type": "boolean",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "emergencytemp": {
        "name": "emergencytemp",
        "fullname": "emergency temperature",
        "circuit": "",
        "type": "number",
        "min": 15,
        "max": 70,
        "uom": "°C",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "meterheat": {
        "name": "meterheat",
        "fullname": "meter heating",
        "circuit": "",
        "type": "number",
        "uom": "kWh",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "dhw.meter": {
        "name": "meter",
        "fullname": "dhw meter",
        "circuit": "dhw",
        "type": "number",
        "uom": "kWh",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "gasmeterheat": {
        "name": "gasmeterheat",
        "fullname": "gas meter heating",
        "circuit": "",
        "type": "number",
        "uom": "kWh",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "dhw.gasmeter": {
        "name": "gasmeter",
        "fullname": "dhw gas meter",
        "circuit": "dhw",
        "type": "number",
        "uom": "kWh",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "nrgheat2": {
        "name": "nrgheat2",
        "fullname": "energy heating 2",
        "circuit": "",
        "type": "number",
        "uom": "kWh",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "dhw.nrg2": {
        "name": "nrg2",
        "fullname": "dhw energy 2",
        "circuit": "dhw",
        "type": "number",
        "uom": "kWh",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "dhw.tapactivated": {
        "name": "tapactivated",
        "fullname": "dhw turn on/off",
        "circuit": "dhw",
        "type": "boolean",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "dhw.settemp": {
        "name": "settemp",
        "fullname": "dhw set temperature",
        "circuit": "dhw",
        "value": 61,
        "type": "number",
        "uom": "°C",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "dhw.seltemp": {
        "name": "seltemp",
        "fullname": "dhw selected temperature",
        "circuit": "dhw",
        "value": 60,
        "type": "number",
        "min": 0,
        "max": 254,
        "uom": "°C",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "dhw.seltemplow": {
        "name": "seltemplow",
        "fullname": "dhw selected lower temperature",
        "circuit": "dhw",
        "type": "number",
        "min": 0,
        "max": 254,
        "uom": "°C",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "dhw.tempecoplus": {
        "name": "tempecoplus",
        "fullname": "dhw selected eco+ temperature",
        "circuit": "dhw",
        "type": "number",
        "min": 0,
        "max": 254,
        "uom": "°C",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "dhw.seltempoff": {
        "name": "seltempoff",
        "fullname": "dhw selected temperature for off",
        "circuit": "dhw",
        "type": "number",
        "uom": "°C",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "dhw.seltempsingle": {
        "name": "seltempsingle",
        "fullname": "dhw single charge temperature",
        "circuit": "dhw",
        "type": "number",
        "min": 0,
        "max": 254,
        "uom": "°C",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "dhw.solartemp": {
        "name": "solartemp",
        "fullname": "dhw solar boiler temperature",
        "circuit": "dhw",
        "type": "number",
        "uom": "°C",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "dhw.type": {
        "name": "type",
        "fullname": "dhw type",
        "circuit": "dhw",
        "index": 3,
        "enum": [
            "off",
            "flow",
            "buffered flow",
            "buffer",
            "layered buffer"
        ],
        "value": "buffer",
        "type": "enum",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "dhw.comfort": {
        "name": "comfort",
        "fullname": "dhw comfort",
        "circuit": "dhw",
        "index": 0,
        "enum": [
            "hot",
            "eco",
            "intelligent"
        ],
        "value": "hot",
        "type": "enum",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "dhw.comfort1": {
        "name": "comfort1",
        "fullname": "dhw comfort mode",
        "circuit": "dhw",
        "type": "enum",
        "enum": [
            "high comfort",
            "eco"
        ],
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "dhw.flowtempoffset": {
        "name": "flowtempoffset",
        "fullname": "dhw flow temperature offset",
        "circuit": "dhw",
        "value": 20,
        "type": "number",
        "min": 0,
        "max": 100,
        "uom": "°C",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "dhw.chargeoptimization": {
        "name": "chargeoptimization",
        "fullname": "dhw charge optimization",
        "circuit": "dhw",
        "type": "boolean",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "dhw.maxpower": {
        "name": "maxpower",
        "fullname": "dhw max power",
        "circuit": "dhw",
        "type": "number",
        "min": 17,
        "max": 100,
        "uom": "%",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "dhw.maxtemp": {
        "name": "maxtemp",
        "fullname": "dhw maximum temperature",
        "circuit": "dhw",
        "type": "number",
        "min": 0,
        "max": 80,
        "uom": "°C",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "dhw.circpump": {
        "name": "circpump",
        "fullname": "dhw circulation pump available",
        "circuit": "dhw",
        "bool": true,
        "index": 1,
        "value": "on",
        "type": "boolean",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "dhw.chargetype": {
        "name": "chargetype",
        "fullname": "dhw charging type",
        "circuit": "dhw",
        "index": 1,
        "enum": [
            "chargepump",
            "3-way valve"
        ],
        "value": "3-way valve",
        "type": "enum",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "dhw.hyston": {
        "name": "hyston",
        "fullname": "dhw hysteresis on temperature",
        "circuit": "dhw",
        "value": -11,
        "type": "number",
        "min": -126,
        "max": 126,
        "uom": "°C",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "dhw.hystoff": {
        "name": "hystoff",
        "fullname": "dhw hysteresis off temperature",
        "circuit": "dhw",
        "value": 0,
        "type": "number",
        "min": -126,
        "max": 126,
        "uom": "°C",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "dhw.disinfectiontemp": {
        "name": "disinfectiontemp",
        "fullname": "dhw disinfection temperature",
        "circuit": "dhw",
        "value": 70,
        "type": "number",
        "min": 60,
        "max": 80,
        "uom": "°C",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "dhw.circmode": {
        "name": "circmode",
        "fullname": "dhw circulation pump mode",
        "circuit": "dhw",
        "index": 2,
        "enum": [
            "off",
            "1x3min",
            "2x3min",
            "3x3min",
            "4x3min",
            "5x3min",
            "6x3min",
            "continuous"
        ],
        "value": "2x3min",
        "type": "enum",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "dhw.circ": {
        "name": "circ",
        "fullname": "dhw circulation active",
        "circuit": "dhw",
        "bool": false,
        "index": 0,
        "value": "off",
        "type": "boolean",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "dhw.curtemp": {
        "name": "curtemp",
        "fullname": "dhw current intern temperature",
        "circuit": "dhw",
        "value": 46.8,
        "type": "number",
        "uom": "°C",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "dhw.curtemp2": {
        "name": "curtemp2",
        "fullname": "dhw current extern temperature",
        "circuit": "dhw",
        "value": 60.1,
        "type": "number",
        "uom": "°C",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "dhw.curflow": {
        "name": "curflow",
        "fullname": "dhw current tap water flow",
        "circuit": "dhw",
        "value": 0.0,
        "type": "number",
        "uom": "l/min",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "dhw.storagetemp1": {
        "name": "storagetemp1",
        "fullname": "dhw storage intern temperature",
        "circuit": "dhw",
        "value": 46.6,
        "type": "number",
        "uom": "°C",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "dhw.storagetemp2": {
        "name": "storagetemp2",
        "fullname": "dhw storage extern temperature",
        "circuit": "dhw",
        "value": 59.9,
        "type": "number",
        "uom": "°C",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "dhw.activated": {
        "name": "activated",
        "fullname": "dhw activated",
        "circuit": "dhw",
        "bool": true,
        "index": 1,
        "value": "on",
        "type": "boolean",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "dhw.onetime": {
        "name": "onetime",
        "fullname": "dhw one time charging",
        "circuit": "dhw",
        "bool": false,
        "index": 0,
        "value": "off",
        "type": "boolean",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "dhw.disinfecting": {
        "name": "disinfecting",
        "fullname": "dhw disinfecting",
        "circuit": "dhw",
        "bool": false,
        "index": 0,
        "value": "off",
        "type": "boolean",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "dhw.charging": {
        "name": "charging",
        "fullname": "dhw charging",
        "circuit": "dhw",
        "bool": false,
        "index": 0,
        "value": "off",
        "type": "boolean",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "dhw.recharging": {
        "name": "recharging",
        "fullname": "dhw recharging",
        "circuit": "dhw",
        "bool": false,
        "index": 0,
        "value": "off",
        "type": "boolean",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "dhw.tempok": {
        "name": "tempok",
        "fullname": "dhw temperature ok",
        "circuit": "dhw",
        "bool": true,
        "index": 1,
        "value": "on",
        "type": "boolean",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "dhw.active": {
        "name": "active",
        "fullname": "dhw active",
        "circuit": "dhw",
        "bool": false,
        "index": 0,
        "value": "off",
        "type": "boolean",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "dhw.3wayvalve": {
        "name": "3wayvalve",
        "fullname": "dhw 3-way valve active",
        "circuit": "dhw",
        "bool": false,
        "index": 0,
        "value": "off",
        "type": "boolean",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "dhw.mixertemp": {
        "name": "mixertemp",
        "fullname": "dhw mixer temperature",
        "circuit": "dhw",
        "type": "number",
        "uom": "°C",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "dhw.cylmiddletemp": {
        "name": "cylmiddletemp",
        "fullname": "dhw cylinder middle temperature (TS3)",
        "circuit": "dhw",
        "type": "number",
        "uom": "°C",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "dhw.starts": {
        "name": "starts",
        "fullname": "dhw starts",
        "circuit": "dhw",
        "value": 29534,
        "type": "number",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "dhw.workm": {
        "name": "workm",
        "fullname": "dhw active time",
        "circuit": "dhw",
        "value": 192922,
        "type": "number",
        "uom": "minutes",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "nompower": {
        "name": "nompower",
        "fullname": "nominal Power",
        "circuit": "",
        "value": 30,
        "type": "number",
        "min": 0,
        "max": 254,
        "uom": "kW",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "nrgtotal": {
        "name": "nrgtotal",
        "fullname": "total energy",
        "circuit": "",
        "value": 67.70,
        "type": "number",
        "uom": "kWh",
        "readable": true,
        "writeable": false,
        "visible": true
    },
    "nrgheat": {
        "name": "nrgheat",
        "fullname": "energy heating",
        "circuit": "",
        "value": 67.23,
        "type": "number",
        "min": 0,
        "max": 10000000,
        "uom": "kWh",
        "readable": true,
        "writeable": true,
        "visible": true
    },
    "dhw.nrg": {
        "name": "nrg",
        "fullname": "dhw energy",
        "circuit": "dhw",
        "value": 0.47,
        "type": "number",
        "min": 0,
        "max": 10000000,
        "uom": "kWh",
        "readable": true,
        "writeable": true,
        "visible": true
    }
}`;
