version: "3"
services:
  ems-esp-exporter:
    # Uncomment the following and comment "build" line to use ready-made image
    #image: poelstra/ems-esp-exporter:latest
    build: .
    restart: on-failure
    environment:
      # To override these, edit them here, or better: just create
      # a file `.env` next to this compose file and put name=value lines in it.

      # URL on which EMS-ESP can be reached
      EMS_ESP_URL: ${EMS_ESP_URL:-http://ems-esp.local}

      # (Optional) Port to listen for `/metrics` requests
      METRICS_PORT: ${METRICS_PORT:-3000}

      # (Optional) Location of custom dump_entities.csv, if needed.
      # Note: only needed for EMS-ESP <3.7.0
      # Download the latest from https://docs.emsesp.org/data/dump_entities.csv
      ENTITIES_CSV: ${ENTITIES_CSV:-/app/config/dump_entities.csv}

    ports:
      - ${METRICS_PORT:-3000}:${METRICS_PORT:-3000}/tcp
